# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thue
email: MarcoBrack93@gmail.com
description: "A puzzle-game based on NP-hard problems from theoretical computer science"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thue.systems" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: turbopope
github_username:  turbopope

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
kramdown:
  auto_ids: true

latest_version:
  code: 0.9.8
  anchor: version-098 # This is generated by kramdown from the headers in the changelog source file
  date: 2016-11-06
  dropbox_link: "https://www.dropbox.com/s/oyjnx2qlrsizyhm/thue_0-9-8.apk?dl=1" # Make sure the `dl=1` query param is there
bugtracker: https://gitlab.uni-koblenz.de/mbrack/thue/issues
website_repo: https://github.com/turbopope/thue.systems
app_repo: https://gitlab.uni-koblenz.de/mbrack/thue/
html_tags: "App, Android, Game, Computer Science"
html_author: "Marco Brack"
